// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZSyfJseHBrENS7TavGgr7lVxjkgyHjIU',
    appId: '1:44372353100:web:0461cc9a42963797d314e9',
    messagingSenderId: '44372353100',
    projectId: 'notes-app-ad612',
    authDomain: 'notes-app-ad612.firebaseapp.com',
    storageBucket: 'notes-app-ad612.appspot.com',
    measurementId: 'G-2MNMJK80QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUsbUybIOTCR6KhAjhgXduE3X0rvUx18',
    appId: '1:44372353100:android:c603154ae9e82904d314e9',
    messagingSenderId: '44372353100',
    projectId: 'notes-app-ad612',
    storageBucket: 'notes-app-ad612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABvknNNRNT-4_fMpUroAiZEfm9inW5W9s',
    appId: '1:44372353100:ios:a9728d34255fd108d314e9',
    messagingSenderId: '44372353100',
    projectId: 'notes-app-ad612',
    storageBucket: 'notes-app-ad612.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABvknNNRNT-4_fMpUroAiZEfm9inW5W9s',
    appId: '1:44372353100:ios:a9728d34255fd108d314e9',
    messagingSenderId: '44372353100',
    projectId: 'notes-app-ad612',
    storageBucket: 'notes-app-ad612.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZSyfJseHBrENS7TavGgr7lVxjkgyHjIU',
    appId: '1:44372353100:web:e979b7c893e6c967d314e9',
    messagingSenderId: '44372353100',
    projectId: 'notes-app-ad612',
    authDomain: 'notes-app-ad612.firebaseapp.com',
    storageBucket: 'notes-app-ad612.appspot.com',
    measurementId: 'G-GF5H39HVPT',
  );
}
